config/routes.rb
Rails.application.routes.draw do
  resources :lyrics, only: [:destroy] do
    collection do
      get :random
    end
  end
  root 'lyrics#index'
end

app/models/lyric.rb
class Lyric < ActiveRecord::Base
  include RankedModel
  ranks :row_order
end

app/models/lyric_maker.rb
class String
  def whole_space_to_half_space
    self.gsub(/　/, ' ')
  end
end

class LyricMaker < Mechanize
  @@phrases = []
  def self.get_each_lyric
    url = 'http://j-lyric.net/artist/a000603/'
    links = []
    agent = Mechanize.new
    current_page = agent.get(url)
    elements = current_page.search('.bdy .ttl a')
    p elements
    elements.each do |ele|
      links << ele[:href]
    end

    links.each do |link|
      get_lyric('http://j-lyric.net' + link)
    end
  end

  def self.just_deviding_word(lyrics)
    lyrics.each_line do |line|
      block = line.split
      block.each do |phrase|
        unless phrase =~/["#$%&'()※△\*\+\-\.,\/:;<=>?@\[\\\]^_`{|}~]/
          lyric = Lyric.new
          if phrase =~ /　/
            new_b = phrase.whole_space_to_half_space
            array = new_b.split
            array.each do |phrase|
              lyric.word
              lyric.save if lyric.word
            end
          else
            lyric.word = phrase
            lyric.save if lyric.word
          end
        end
      end
    end
  end

  # not used
  def self.separate_english_word(lyrics)
    lyrics.each_line do |line|
      if line != ""
        lyric = Lyric.new
        lyric.word = line
        lyric.save
      end
    end
  end


  def self.get_lyric(link)
    agent = Mechanize.new
    page = agent.get(link)
    lyrics = page.at('#Lyric').inner_text
    #separate_english_word(lyrics)
    just_deviding_word(lyrics)
  end
end





# LyricMaker.get_each_url(spitz_url)
# LyricMaker.sort_words

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
  def index
    @lyrics1 = Lyric.find(Lyric.pluck(:id).shuffle[0..19])
    @lyrics2 = Lyric.find(Lyric.pluck(:id).shuffle[0..9])
  end

  def random
    @lyrics3 = Lyric.find(Lyric.pluck(:id).shuffle[0..9])
  end

  private
  def fruit_params
    params.require(:lyric).permit(:word)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lyrics_helper.rb
module LyricsHelper
end

app/views/common/_header.html.haml
%header.mainheader.clearfix
  %h3.title Spitz Lyric Maker
  .reload-button
    %button
      = link_to 'Reload', random_lyrics_path, remote: true

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Lyricmaker
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'common/header'
    = yield

app/views/lyrics/_lyric.html.haml
- hidden_index = lyric_counter += 1
= form_for lyric do |f|
  %li.ui-state-default
    = f.text_field :word, placeholder: lyric
    = button_tag 'remove', class: 'remove-button'
/ renderが隠れindexをもってる

app/views/lyrics/destroy.js.erb
$('#sortable2').html("<%= j(render partial: 'lyrics/lyric', collection: @lyrics1)%>")

app/views/lyrics/index.html.haml
%h1 You are a stargazer.
.lyric-table
  %ul#sortable1.connectedSortable
    - lyrics_couter = 0
    = render partial: 'lyric', collection: @lyrics1
  %ul#sortable2.connectedSortable
    = render partial: 'lyric', collection: @lyrics2

app/views/lyrics/random.js.erb
$('#sortable2').html("<%= j(render partial: 'lyrics/lyric', collection: @lyrics3)%>")